# Generated by Django 4.0.5 on 2022-07-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_description_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='created_by',
        ),
    ]
